### ISSUE TITLE
dev setup and startup error

### ISSUE THREAD

**Issue by bsr203** [vincentriemer/personal-blog#1]
Hi Vincent,

I came to this repo while looking for a good example usage of relay. Thanks for open sourcing it. 

I have an issue trying it out though. I am not familiar with all the docker options, but I tried,

```
docker-compose -f development.yml up  

Pulling db (sameersbn/postgresql:latest)...
Pulling repository docker.io/sameersbn/postgresql
1da0f78d061e: Pulling image (latest) from docker.io/sameersbn/postgresql, endpoi1da0f78d061e: Download complete
d3a1f33e8a5a: Download complete
c22013c84729: Download complete

...
3d1e86b683ea: Download complete
Status: Downloaded newer image for sameersbn/postgresql:latest
Creating relaypersonalblog_db_1...
Creating relaypersonalblog_public-backend_1...
Creating relaypersonalblog_admin-backend_1...
Creating relaypersonalblog_admin-frontend_1...
Creating relaypersonalblog_public-frontend_1...
Attaching to
```

when loaded the admin-frontend:

http://dockerhost:3003/

I see the below error in dev tools console

```
RelayPendingQueryTracker.js:162 Server request for query `App` failed for the following reasons:

1. select "posts".* from "posts" order by "created_at" desc limit $1 - relation "posts" does not exist
   gment0h3o9z on User{_postss5kme8:posts(first:5){edges{node{i
```

can you please tell a bit about your development flow. Where/how can I see the server error or how do you debug server side? How to correct the above error?

thanks again for your time and making it open.

bsr.

**Comment by vincentriemer** [comment]
My bet is you haven't run the database migrations yet, you'll want to run the following commands:

```
cd personal-blog/database
npm install knex pg
npm install -g knex
knex migrate:latest
```

I'm still in pretty heavy development mode so don't be surprised if I commit something that breaks everything ;)

**Comment by vincentriemer** [comment]
Also in regards to debugging the server side error this is actually an issue related to relay as it catches all server errors and puts it in the graphql response. This is apparently a known issue and the team is working on it.

**Comment by bsr203** [comment]
thanks a ton for your time and help. I am watching the repo and learning a lot through it. thanks again bsr.
